nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/wombelix/fork_harvester_harvester-ui-extension/main-head/extensions/harvester/1.8.0-dev
  compressedEndpoint: >-
    https://raw.githubusercontent.com/wombelix/fork_harvester_harvester-ui-extension/main-head/extensions/harvester/1.8.0-dev.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/display-name: Harvester
    catalog.cattle.io/kube-version: ">= 1.16.0-0"
    catalog.cattle.io/rancher-version: ">= 2.14.0-0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
